"""
Blue Team ML Detector

Trains a fraud classifier on the synthetic payment universe
generated by the Red Team simulation layer.
"""

from pathlib import Path

import joblib
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder


# ============================================================
# PATHS
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

DATA_FILE = (
    BASE_DIR
    / "data"
    / "synthetic_payments.csv"
)

MODEL_DIR = BASE_DIR / "models"

MODEL_FILE = MODEL_DIR / "fraud_detector.joblib"


# ============================================================
# LOAD DATA
# ============================================================

print()
print("=" * 60)
print("ADAPTIVE ADVERSARIAL PAYMENT DEFENSE LAB")
print("BLUE TEAM — ML DETECTOR TRAINING")
print("=" * 60)
print()

df = pd.read_csv(DATA_FILE)

print(f"Dataset loaded: {len(df):,} transactions")
print()


# ============================================================
# FEATURES
# ============================================================

FEATURES = [
    "amount",
    "merchant_category",
    "country",
    "payment_method",
    "velocity_1h",
    "device_age_days",
    "location_change",
    "new_payment_method",
    "account_age_days",
    "merchant_anomaly",
    "amount_anomaly",
]

TARGET = "is_fraud"


X = df[FEATURES]
y = df[TARGET]


# ============================================================
# TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y,
)

print(f"Training samples: {len(X_train):,}")
print(f"Testing samples:  {len(X_test):,}")
print()


# ============================================================
# FEATURE TYPES
# ============================================================

categorical_features = [
    "merchant_category",
    "country",
    "payment_method",
]

numeric_features = [
    "amount",
    "velocity_1h",
    "device_age_days",
    "location_change",
    "new_payment_method",
    "account_age_days",
    "merchant_anomaly",
    "amount_anomaly",
]


# ============================================================
# PREPROCESSING
# ============================================================

preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features,
        ),
        (
            "numeric",
            "passthrough",
            numeric_features,
        ),
    ]
)


# ============================================================
# MODEL
# ============================================================

classifier = RandomForestClassifier(
    n_estimators=250,
    max_depth=12,
    min_samples_leaf=3,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1,
)


# ============================================================
# COMPLETE PIPELINE
# ============================================================

model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor,
        ),
        (
            "classifier",
            classifier,
        ),
    ]
)


# ============================================================
# TRAIN
# ============================================================

print("Training Blue-Team detector...")
print()

model.fit(
    X_train,
    y_train,
)


# ============================================================
# PREDICTION
# ============================================================

y_pred = model.predict(X_test)


# ============================================================
# METRICS
# ============================================================

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0,
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0,
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0,
)


# ============================================================
# FALSE POSITIVE RATE
# ============================================================

tn, fp, fn, tp = confusion_matrix(
    y_test,
    y_pred,
).ravel()

false_positive_rate = (
    fp / (fp + tn)
    if (fp + tn) > 0
    else 0
)


# ============================================================
# RESULTS
# ============================================================

print("=" * 60)
print("BLUE-TEAM RESULTS")
print("=" * 60)

print()

print(
    f"Precision:          {precision * 100:.2f}%"
)

print(
    f"Recall:             {recall * 100:.2f}%"
)

print(
    f"F1 Score:           {f1 * 100:.2f}%"
)

print(
    f"False Positive Rate:{false_positive_rate * 100:.2f}%"
)

print()

print("Confusion Matrix:")
print()

print(
    confusion_matrix(
        y_test,
        y_pred,
    )
)

print()

print("Classification Report:")
print()

print(
    classification_report(
        y_test,
        y_pred,
        target_names=[
            "Legitimate",
            "Fraud",
        ],
        zero_division=0,
    )
)


# ============================================================
# SAVE MODEL
# ============================================================

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

joblib.dump(
    model,
    MODEL_FILE,
)

print("=" * 60)
print("MODEL SAVED")
print("=" * 60)

print()

print(
    f"Model: {MODEL_FILE}"
)

print()