services:
  mysql:
    image: mysql:8.4
    container_name: apre-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apre_db
      MYSQL_USER: apre
      MYSQL_PASSWORD: apre123

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: